[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
mry = "0.2"
dirs = "4.0.0"
tracing = "0.1.35"

domain = { path = "../domain" }
