[package]
name = "port"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"

domain = { path = "../domain"}
mry = "0.2.4"
