name: "app test"

on:
  push:
    branches:
      - "master"
    paths:
      - app/**
      - .github/workflows/ci.yaml

env:
  RUST_VERSION: 1.62.0

jobs:
  fmt-and-clippy:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup rust ${{ env.RUST_VERSION }}
        uses: ./.github/actions/setup_rust
        with:
          rust-version: ${{ env.RUST_VERSION }}
          rust-components: rustfmt, clippy

      - name: Format
        run: cargo fmt

      - name: Apply format changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ':green_heart: Auto format'
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run clippy
        run: cargo clippy

  unit-test:
    runs-on: ubuntu-latest

    needs: [fmt-and-clippy]

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup rust ${{ env.RUST_VERSION }}
        uses: ./.github/actions/setup_rust
        with:
          rust-version: ${{ env.RUST_VERSION }}

      - name: Run test
        run: cargo test --all -- --nocapture